spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:screencapture}}
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER:}
    password: ${PGPASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  h2:
    console:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
